name: Compiler

on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: |
            tesi.tex
            presentazione/presentazione.tex
          work_in_root_file_dir: true

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v7
        with:
          name: thesis-pdf
          path: tesi.pdf
          archive: false

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v7
        with:
          name: presentation-pdf
          path: presentazione/presentazione.pdf
          archive: false
